# Generated by Django 5.1.6 on 2025-02-09 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
    ]
